name: CI

# This workflow run tests and build for each push

on:
  push:
    branches:
      - main
jobs:
  test_ova:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
    
      - name: Update local toolchain
        run: |
          rustup update
          rustup component add clippy
          rustup install nightly
          cargo install cargo-llvm-cov --locked

      - name: Toolchain info
        run: |
          cargo --version --verbose
          rustc --version
          cargo clippy --version          

      - name: Lint
        run: |
          cargo fmt -- --check
          cargo clippy -- -D warnings          

      - name: Test
        run: |
          mkdir coverage
          cargo llvm-cov --lcov --output-path ./coverage/lcov.info 

      - name: Build
        run: |
          cargo build --release 

      - name: Coveralls GitHub Action
        uses: coverallsapp/github-action@v2
